# Generated by Django 2.1.1 on 2022-06-23 12:08

from django.db import migrations, models
import realtors.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20220622_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[realtors.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[realtors.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[realtors.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[realtors.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[realtors.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[realtors.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', validators=[realtors.validators.validate_file_size]),
        ),
    ]
